name: void_space
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  sqlite3_flutter_libs: ^0.5.21
  path: ^1.8.3
  path_provider: ^2.1.2
  google_fonts: ^6.1.0
  flutter_staggered_grid_view: ^0.7.0
  http: ^1.1.0
  html: ^0.15.4
  url_launcher: ^6.2.1
  local_auth: ^2.1.6
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true