name: void_space
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  google_fonts: ^6.1.0
  flutter_staggered_grid_view: ^0.7.0
  http: ^1.1.0
  html: ^0.15.4
  url_launcher: ^6.2.1
  open_filex: ^4.6.0
  local_auth: ^2.1.6
  shared_preferences: ^2.5.4
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  provider: ^6.1.5+1
  share_plus: ^12.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/